name: Deploy Flutter Web

on:
  push:
    branches: 
      - master
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Chekout
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    
    - name: Build Flutter Web
      run: 
        flutter config --enable-web
        flutter pub get
        flutter build web --release
    
    - name: Firebase deploy
      run:
        sudo npm install -g firebase-tools
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}